name: Build, Test & Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/API
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
        
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
         
      - name: Test & Generate Coverage
        run: dotnet test --no-build -v minimal --logger trx --collect:"XPlat Code Coverage" --results-directory ./coverage
     
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
        working-directory: ./src/API
          directory: ./coverage      
          fail_ci_if_error: true
    
